all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    raspberry_pi3:
      hosts:
        wifi_ap:
          # 192.168.2.2 - IP getting via Mac Internet Sharing
          # and direct Ethernet connection of my raspberrypi
          ansible_host: 192.168.2.2
