---
- hosts: raspberrypi_3

  vars_files:
    - vars/vault.yml

  roles:
    - role: drew1kun.wifi_ap
      wifi_ap_essid: "{{ vault_wifi_ap_essid }}"
      wifi_ap_passphrase: "{{ vault_wifi_ap_passphrase }}"
      wifi_ap_WAN: wlan0
      wifi_ap_WLAN: wlan1

      # Override the list of wifi networks to be configured byt rip3_network role
      wif_ap__rpi3_network_wifi_APs: "{{  vault_wifi_ap__rpi3_network_wifi_APs }}"
